### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by jaroslavas** [ufficioprogettiperduti/Scalable-Pen-Plotter#1]
First of all, project looks really cool!
Are there any plans to make instructions? Or at least a Bill Of Material for buying everything that can't be printed?

**Comment by ufficioprogettiperduti** [comment]
HelloOoOo Happy to hear you like our project! There is the build on materials on [prusaprinters](https://www.prusaprinters.org/prints/4836-did-scalable-pen-plotter) as well as on [thingiverse](https://www.thingiverse.com/thing:3789969). Instructions wise we have some photos with step by step assembly [here](https://drive.google.com/drive/folders/1meqg_gCzxqIbxvdvVfCSB17FMGs8Z9P_?usp=sharing). We had plans about writing a detailed pdf with these photos but as we are working on another similar but different plotter we never came around to finish it.
Hope to have helped!
